<?php

namespace Database\Seeders;

use App\Models\Marca;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MarcaSeed extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $marcas = [
            ['nombre' => 'Intel', 'descripcion' => 'Fabricante líder de microprocesadores y chips para computadoras.'],
            ['nombre' => 'AMD', 'descripcion' => 'Competidor de Intel, conocido por procesadores y tarjetas gráficas.'],
            ['nombre' => 'NVIDIA', 'descripcion' => 'Especialista en unidades de procesamiento gráfico (GPU).'],
            ['nombre' => 'ASUS', 'descripcion' => 'Fabricante de placas base, laptops y tarjetas gráficas.'],
            ['nombre' => 'Gigabyte', 'descripcion' => 'Reconocido fabricante de hardware, especialmente placas base y GPUs.'],
            ['nombre' => 'MSI', 'descripcion' => 'Marca enfocada en hardware para gaming y profesionales.'],
            ['nombre' => 'Corsair', 'descripcion' => 'Proveedor de memorias RAM, fuentes de poder y periféricos.'],
            ['nombre' => 'Kingston', 'descripcion' => 'Fabricante líder en memorias RAM y almacenamiento.'],
            ['nombre' => 'Crucial', 'descripcion' => 'División de Micron especializada en memorias y SSDs.'],
            ['nombre' => 'Samsung', 'descripcion' => 'Empresa global que produce memorias, SSDs y otros componentes electrónicos.'],
            ['nombre' => 'Seagate', 'descripcion' => 'Especialista en discos duros y unidades de almacenamiento.'],
            ['nombre' => 'Western Digital', 'descripcion' => 'Fabricante de discos duros, SSDs y soluciones de almacenamiento.'],
            ['nombre' => 'Toshiba', 'descripcion' => 'Fabricante de discos duros y componentes electrónicos.'],
            ['nombre' => 'SanDisk', 'descripcion' => 'Marca de almacenamiento flash y tarjetas de memoria.'],
            ['nombre' => 'EVGA', 'descripcion' => 'Fabricante de tarjetas gráficas, fuentes de poder y hardware para gaming.'],
            ['nombre' => 'Cooler Master', 'descripcion' => 'Proveedor de soluciones de enfriamiento, gabinetes y periféricos.'],
            ['nombre' => 'Logitech', 'descripcion' => 'Empresa líder en periféricos como teclados, ratones y cámaras.'],
            ['nombre' => 'TP-Link', 'descripcion' => 'Fabricante de dispositivos de red como routers y switches.'],
            ['nombre' => 'Zotac', 'descripcion' => 'Especialista en tarjetas gráficas y mini PCs.'],
            ['nombre' => 'Philips', 'descripcion' => 'Empresa tecnológica que también produce componentes electrónicos y accesorios.'],
            ['nombre' => 'Dell', 'descripcion' => 'Fabricante global de computadoras, servidores y accesorios.'],
            ['nombre' => 'HP', 'descripcion' => 'Multinacional que fabrica PCs, impresoras y consumibles.'],
            ['nombre' => 'Lenovo', 'descripcion' => 'Empresa líder en computadoras portátiles y de escritorio.'],
            ['nombre' => 'Acer', 'descripcion' => 'Fabricante de PCs, laptops y componentes electrónicos.'],
            ['nombre' => 'Apple', 'descripcion' => 'Innovador en computación personal y dispositivos electrónicos.'],
            ['nombre' => 'Microsoft', 'descripcion' => 'Desarrollador de software y fabricante de hardware como Surface.'],
            ['nombre' => 'Razer', 'descripcion' => 'Marca premium especializada en hardware para gamers.'],
            ['nombre' => 'SteelSeries', 'descripcion' => 'Proveedor de periféricos para gaming de alta calidad.'],
            ['nombre' => 'HyperX', 'descripcion' => 'Línea de productos para gamers, incluyendo memorias y accesorios.'],
            ['nombre' => 'BenQ', 'descripcion' => 'Fabricante de monitores, proyectores y periféricos.'],
            ['nombre' => 'Epson', 'descripcion' => 'Empresa reconocida en impresoras y consumibles.'],
            ['nombre' => 'Brother', 'descripcion' => 'Marca de impresoras, multifuncionales y consumibles.'],
            ['nombre' => 'Canon', 'descripcion' => 'Líder mundial en impresión y cámaras digitales.'],
            ['nombre' => 'Lexmark', 'descripcion' => 'Especialista en impresoras y consumibles para oficina.'],
            ['nombre' => 'Sharp', 'descripcion' => 'Fabricante de productos electrónicos y de oficina.'],
            ['nombre' => 'Panasonic', 'descripcion' => 'Multinacional con variedad de productos electrónicos.'],
            ['nombre' => 'Sony', 'descripcion' => 'Empresa global de electrónica, entretenimiento y hardware.'],
            ['nombre' => 'JBL', 'descripcion' => 'Marca de audio y altavoces para consumidores y profesionales.'],
            ['nombre' => 'Sennheiser', 'descripcion' => 'Especialista en auriculares y sistemas de audio profesionales.'],
            ['nombre' => 'ASRock', 'descripcion' => 'Fabricante de placas base y mini PCs.'],
            ['nombre' => 'ADATA', 'descripcion' => 'Proveedores de memoria y almacenamiento para PC.'],
            ['nombre' => 'G.Skill', 'descripcion' => 'Marca reconocida de memoria RAM para gaming y alto rendimiento.'],
            ['nombre' => 'Thermaltake', 'descripcion' => 'Proveedor de soluciones de enfriamiento y gabinetes.'],
            ['nombre' => 'Be Quiet!', 'descripcion' => 'Marca de fuentes de poder y soluciones de enfriamiento silencioso.'],
            ['nombre' => 'NZXT', 'descripcion' => 'Fabricante de gabinetes y accesorios para PC gamers.'],
            ['nombre' => 'Phanteks', 'descripcion' => 'Especializada en gabinetes y refrigeración.'],
            ['nombre' => 'Fractal Design', 'descripcion' => 'Proveedor de gabinetes y soluciones de refrigeración premium.'],
            ['nombre' => 'SilverStone', 'descripcion' => 'Fabricante de gabinetes y fuentes de poder para PC.'],
            ['nombre' => 'BitFenix', 'descripcion' => 'Proveedor de gabinetes y accesorios para PC.'],
            ['nombre' => 'Patriot', 'descripcion' => 'Fabricante de memorias y almacenamiento.'],
            ['nombre' => 'Lexar', 'descripcion' => 'Tarjetas de memoria y dispositivos de almacenamiento.'],
            ['nombre' => 'PNY', 'descripcion' => 'Fabricante de memorias, tarjetas gráficas y almacenamiento.'],
            ['nombre' => 'Seasonic', 'descripcion' => 'Fabricante reconocido de fuentes de poder.'],
            ['nombre' => 'Antec', 'descripcion' => 'Proveedor de fuentes de poder y gabinetes.'],
            ['nombre' => 'DeepCool', 'descripcion' => 'Soluciones de enfriamiento y gabinetes.'],
            ['nombre' => 'Noctua', 'descripcion' => 'Refrigeración silenciosa y efectiva para PC.'],
            ['nombre' => 'Arctic', 'descripcion' => 'Sistemas de enfriamiento y ventiladores accesibles.'],
            ['nombre' => 'LG', 'descripcion' => 'Fabricante de monitores, hardware y electrónica.'],
            ['nombre' => 'AOC', 'descripcion' => 'Fabricante de monitores económicos y de gama media.'],
            ['nombre' => 'ViewSonic', 'descripcion' => 'Monitores y proyectores para uso profesional y educativo.'],
            ['nombre' => 'Blue Microphones', 'descripcion' => 'Micrófonos para grabación y streaming.'],
            ['nombre' => 'Elgato', 'descripcion' => 'Equipos para streaming y captura de video.'],
            ['nombre' => 'Samsung EVO', 'descripcion' => 'Unidades SSD de alto rendimiento.'],
            ['nombre' => 'Crucial Ballistix', 'descripcion' => 'Memorias RAM para entusiastas y gamers.'],
            ['nombre' => 'Kingston Canvas', 'descripcion' => 'Tarjetas de memoria para fotografía y video.'],
            ['nombre' => 'SanDisk Ultra', 'descripcion' => 'Tarjetas de memoria y unidades USB.'],
            ['nombre' => 'Seagate IronWolf', 'descripcion' => 'Discos duros para almacenamiento en red (NAS).'],
            ['nombre' => 'Western Digital Red', 'descripcion' => 'Discos duros para NAS y almacenamiento de datos.'],
            ['nombre' => 'Intel Optane', 'descripcion' => 'Tecnología de aceleración y almacenamiento rápido.'],
            ['nombre' => 'Kingston SSDNow', 'descripcion' => 'Unidades SSD para mejora de rendimiento.'],
            ['nombre' => 'ADATA Premier', 'descripcion' => 'Memorias y almacenamiento accesible.'],
            ['nombre' => 'G.Skill Ripjaws', 'descripcion' => 'Memorias RAM para sistemas de alto rendimiento.'],
            ['nombre' => 'Noctua NH-D15', 'descripcion' => 'Disipador por aire de alto rendimiento para CPU.'],
            ['nombre' => 'ASUS Prime', 'descripcion' => 'Placas base para uso general y profesional.'],
            ['nombre' => 'LG UltraGear', 'descripcion' => 'Monitores para gaming y alta resolución.'],
            ['nombre' => 'Acer Predator', 'descripcion' => 'Hardware y laptops para gaming.'],
            ['nombre' => 'Alienware', 'descripcion' => 'Marca de hardware gaming de Dell.'],
            ['nombre' => 'Logitech G', 'descripcion' => 'Línea gaming de periféricos Logitech.'],
            ['nombre' => 'Corsair Vengeance', 'descripcion' => 'Memorias RAM de alto rendimiento para gamers.'],
            ['nombre' => 'Kingston HyperX', 'descripcion' => 'Productos gaming de Kingston.'],
            ['nombre' => 'Dell XPS', 'descripcion' => 'Línea premium de computadoras de Dell.'],
            ['nombre' => 'MSI Gaming', 'descripcion' => 'Hardware especializado en gaming.'],
            ['nombre' => 'Gigabyte AORUS', 'descripcion' => 'Línea gaming de Gigabyte.'],
            ['nombre' => 'ASUS ROG', 'descripcion' => 'Republic of Gamers, línea premium de ASUS.'],
            ['nombre' => 'Zotac Gaming', 'descripcion' => 'Tarjetas gráficas y mini PCs para gaming.'],
            ['nombre' => 'Razer Blade', 'descripcion' => 'Laptops premium para gaming de Razer.'],
            ['nombre' => 'HyperX Cloud', 'descripcion' => 'Auriculares para gaming de HyperX.'],
            ['nombre' => 'SteelSeries Arctis', 'descripcion' => 'Auriculares gaming de alta calidad.'],
            ['nombre' => 'Thermaltake Toughpower', 'descripcion' => 'Fuentes de poder de alto rendimiento.'],
            ['nombre' => 'Cooler Master MasterLiquid', 'descripcion' => 'Sistemas de refrigeración líquida para PC.'],
            ['nombre' => 'Corsair Hydro Series', 'descripcion' => 'Refrigeración líquida para gamers y entusiastas.'],
            ['nombre' => 'NZXT Kraken', 'descripcion' => 'Sistemas avanzados de refrigeración líquida.'],
            ['nombre' => 'Fractal Design Meshify', 'descripcion' => 'Gabinetes con diseño y flujo de aire óptimo.'],
            ['nombre' => 'Phanteks Evolv', 'descripcion' => 'Gabinetes de alta gama para PC.'],
            ['nombre' => 'Be Quiet! Dark Rock', 'descripcion' => 'Sistemas de enfriamiento silenciosos y potentes.'],
            ['nombre' => 'SilverStone Fortress', 'descripcion' => 'Gabinetes de alto rendimiento y diseño robusto.'],
            ['nombre' => 'BitFenix Prodigy', 'descripcion' => 'Gabinetes compactos y funcionales para PC.'],
            ['nombre' => 'Western Digital Blue', 'descripcion' => 'Discos duros para uso general.'],
            ['nombre' => 'Kingston Fury', 'descripcion' => 'Línea de alto rendimiento de Kingston.'],
            ['nombre' => 'ADATA XPG', 'descripcion' => 'Productos gaming de ADATA.'],
            ['nombre' => 'G.Skill Trident Z', 'descripcion' => 'Memorias RAM para gaming y entusiastas.'],
            ['nombre' => 'Thermaltake Riing', 'descripcion' => 'Ventiladores RGB para PC.'],
            ['nombre' => 'Corsair Vengeance RGB', 'descripcion' => 'Memorias RAM con iluminación RGB.'],
            ['nombre' => 'NZXT H-Series', 'descripcion' => 'Gabinetes modernos para PC.'],
            ['nombre' => 'Phanteks P400', 'descripcion' => 'Gabinetes para PC de gama media.'],
            ['nombre' => 'Be Quiet! Pure Rock', 'descripcion' => 'Sistemas de enfriamiento accesibles y silenciosos.'],
            ['nombre' => 'SilverStone Sugo', 'descripcion' => 'Gabinetes compactos para PC.'],
            ['nombre' => 'BitFenix Nova', 'descripcion' => 'Gabinetes económicos y funcionales.'],
            ['nombre' => 'Seasonic Focus', 'descripcion' => 'Fuentes de poder eficientes y confiables.'],
            ['nombre' => 'Cooler Master V Series', 'descripcion' => 'Fuentes de poder para PCs de alto rendimiento.'],
            ['nombre' => 'Corsair CX Series', 'descripcion' => 'Fuentes de poder accesibles y fiables.'],
            ['nombre' => 'SilverStone Strider', 'descripcion' => 'Fuentes de poder modulares para PCs.'],
            ['nombre' => 'Be Quiet! Straight Power', 'descripcion' => 'Fuentes de poder silenciosas y eficientes.'],
            ['nombre' => 'Antec Earthwatts', 'descripcion' => 'Fuentes de poder ecológicas y fiables.'],
            ['nombre' => 'DeepCool DQ Series', 'descripcion' => 'Fuentes de poder para PCs gaming.'],
            ['nombre' => 'Corsair Dominator', 'descripcion' => 'Memorias RAM premium con alto rendimiento.'],
            ['nombre' => 'Kingston Predator', 'descripcion' => 'Memorias RAM para overclocking y gaming.'],
            ['nombre' => 'G.Skill Sniper X', 'descripcion' => 'Memorias RAM para rendimiento y estilo.'],
            ['nombre' => 'ADATA Spectrix', 'descripcion' => 'Memorias RAM con iluminación RGB.'],
            ['nombre' => 'Patriot Viper', 'descripcion' => 'Memorias RAM para gamers y entusiastas.'],
            ['nombre' => 'Crucial MX500', 'descripcion' => 'Unidades SSD confiables para PCs.'],
            ['nombre' => 'Samsung 970 EVO', 'descripcion' => 'Unidades SSD NVMe de alto rendimiento.'],
            ['nombre' => 'Western Digital Blue SN550', 'descripcion' => 'SSD NVMe para uso general.'],
            ['nombre' => 'SanDisk Extreme Pro', 'descripcion' => 'Unidades de almacenamiento rápido y confiable.'],
            ['nombre' => 'Intel SSD 660p', 'descripcion' => 'SSD NVMe para usuarios con presupuesto.'],
            ['nombre' => 'Seagate FireCuda', 'descripcion' => 'Unidades híbridas para gaming y almacenamiento.'],
            ['nombre' => 'Kingston A2000', 'descripcion' => 'SSD NVMe accesible para PCs.'],
            ['nombre' => 'ADATA XPG SX8200 Pro', 'descripcion' => 'SSD NVMe para gamers y profesionales.'],
        ];


        foreach ($marcas as $marca) {
            Marca::create($marca);
        }
        $this->command->info('Marcas creadas o actualizadas exitosamente.');
    }
}
